name: PR Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        run: |
          npm ci
          npm run build --prefix stampy-search
          npm run lint
          npm run test
